name: ui
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - pkgs/main
dependencies:
  - alabaster=0.7.13=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - aom=3.5.0=h63175ca_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h91455d4_4
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.5=hdccc3a2_0
  - bokeh=1.4.0=py38h32f6830_1
  - boost=1.78.0=py38h9e3ed74_0
  - boost-cpp=1.78.0=h9f4b32c_4
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py38hd3f51b4_9
  - bzip2=1.0.8=h0ad9c76_8
  - c-blosc2=2.12.0=h183a6f4_0
  - ca-certificates=2025.8.3=h4c7d964_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h4cb3324_0
  - cfitsio=4.1.0=h5a969a9_0
  - cftime=1.6.1=py38hbdcd294_0
  - charls=2.3.4=h39d44d4_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.1.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cpython=3.8.20=py38hd8ed1ab_2
  - curl=8.1.2=h68f0423_0
  - cvxpy=1.2.1=py38haa244fe_0
  - cvxpy-base=1.2.1=py38hcc40339_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py38h91455d4_0
  - dask=2021.2.0=pyhd8ed1ab_0
  - dask-core=2021.2.0=pyhd8ed1ab_0
  - datashader=0.12.1=pyh44b312d_1
  - datashape=0.5.4=py_1
  - dav1d=1.0.0=h8ffe710_1
  - debugpy=1.8.5=py38h2698bfa_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2021.2.0=py38haa244fe_0
  - docutils=0.16=py38haa244fe_4
  - ecos=2.0.10=py38hbdcd294_1
  - eigen=3.4.0=h91493d7_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=5.1.2=gpl_h97595f5_108
  - ffmpeg-python=0.2.0=py_0
  - fftw=3.3.10=nompi_h89e6982_110
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py38h4cb3324_0
  - freetype=2.14.1=h57928b3_0
  - fsspec=2024.10.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h64bf75a_0
  - glib=2.86.0=ha3795fc_0
  - glib-tools=2.86.0=he647baa_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h57737ce_101
  - holoviews=1.12.7=pyh9f0ad1d_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h0e60522_0
  - idna=3.10=pyhd8ed1ab_0
  - imagecodecs=2022.8.8=py38hd43ff21_5
  - imageio=2.36.0=pyh12aca89_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.12.2=pyh08f2357_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=2.11.3=pyhd8ed1ab_2
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_server=1.24.0=pyhd8ed1ab_0
  - jupyterlab=3.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.5=py38hb1fd069_1
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libavif=0.10.1=h8f5c5bc_2
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.14=hcfcfb64_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.86.0=h5f26cbf_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libitk=5.1.2=h238ef77_0
  - libitk-devel=5.1.2=h0e60522_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libnetcdf=4.8.1=nompi_h8c042bf_106
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.4.0=hc4f729c_5
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.13.8=h741aa76_1
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - llvm-openmp=20.1.8=hfa2b4ca_2
  - llvmlite=0.35.0=py38h34b8924_4
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2r2=0.2.7=pyhd3deb0d_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h294d835_1
  - matplotlib=3.7.1=py38haa244fe_0
  - matplotlib-base=3.7.1=py38hf11a4ad_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - medpy=0.4.0=py38hc3cff20_5
  - metis=5.1.0=h17e2fc9_1007
  - mistune=0.8.4=pyh1a96a4e_1006
  - mkl=2024.2.2=h57928b3_16
  - msgpack-python=1.0.8=py38h7b008d5_0
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbclassic=1.1.0=pyhd8ed1ab_0
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.4.5=pyhd8ed1ab_2
  - nbconvert-core=6.4.5=pyhd8ed1ab_2
  - nbconvert-pandoc=6.4.5=pyhd8ed1ab_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nbsphinx=0.8.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.6.0=nompi_py38h1308d82_102
  - networkx=2.4=py_1
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.52.0=py38h4c96930_0
  - numcodecs=0.12.1=py38h2698bfa_1
  - numpy=1.20.2=py38h09042cb_0
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=3.5.3=h725018a_0
  - osqp=0.6.2.post0=py38h5d928e2_3
  - packaging=25.0=pyh29332c3_1
  - pandas=1.2.3=py38h4c96930_0
  - pandoc=2.19.2=h57928b3_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.8.0=0
  - param=1.13.0=pyh1a96a4e_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py38h3cd753b_3
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.2=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38h4cb3324_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydata-sphinx-theme=0.5.2=pyhd8ed1ab_0
  - pyfftw=0.12.0=py38h46b76f8_3
  - pygments=2.18.0=pyhd8ed1ab_0
  - pymetis=2020.1=py38ha6abf93_5
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py38hd6c051e_5
  - pyqt5-sip=12.12.2=py38hd3f51b4_5
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.20=hfaddaf0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyviz_comms=2.3.2=pyhd8ed1ab_0
  - pywavelets=1.3.0=py38hbdcd294_1
  - pywin32=306=py38hd3f51b4_2
  - pywinpty=2.0.13=py38hd3f51b4_0
  - pyyaml=6.0.2=py38h4cb3324_0
  - pyzmq=26.2.0=py38h3c56b06_0
  - qdldl-python=0.1.5=py38h5d928e2_2
  - qt-main=5.15.8=h720456b_6
  - rechunker=0.3.3=pyhd8ed1ab_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rpds-py=0.20.0=py38h2e0ef18_0
  - scikit-image=0.18.1=py38h4c96930_0
  - scikit-learn=0.22.1=py38h7208079_1
  - scipy=1.9.1=py38h91810f7_0
  - scs=3.2.0=py38h9bc1012_1
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=59.8.0=py38haa244fe_1
  - simpleitk=2.0.2=py38hb12ee37_1
  - sip=6.7.12=py38hd3f51b4_0
  - six=1.16.0=pyh6c4a22f_0
  - sk-video=1.1.10=pyh24bf2e0_4
  - snappy=1.1.10=hfb803bf_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.6=pyhd8ed1ab_0
  - sparse=0.11.2=py_0
  - sphinx=3.5.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.2=py38hbdcd294_0
  - svt-av1=1.4.1=h63175ca_0
  - tbb=2021.13.0=h18a62a1_3
  - tblib=3.0.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tifffile=2022.10.10=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.1=py38h294d835_3
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=15.1.0=py38h91455d4_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - winpty=0.4.3=4
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=0.17.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=h6a83c73_3
  - zarr=2.17.1=pyhd8ed1ab_0
  - zeromq=4.3.5=he0c23c2_3
  - zfp=1.0.1=h2f0f97f_3
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstandard=0.19.0=py38h91455d4_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
    - datashape==0.5.4
    - opencv-python==4.2.0.34
    - rtds-action==1.0.3
    - setuptools-scm==9.2.0

prefix: "C:\\Users\\admin\\anaconda3\\envs\\ui"
